site_name: Hostlist
site_url: https://cloudmesh-ai.github.io/hostlist
repo_url: https://github.com/cloudmesh-ai/hostlist
repo_name: hostlist

theme:
  name: material

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - cloudmesh-ai-theme
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
            docstring_style: google
            group_by_category: true
            members: true
            separate_signature: true
            show_category_heading: true
            show_root_full_path: true
            show_source: true
            show_submodules: true
          paths:
          - src

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_style: colorful
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - admonition
  - pymdownx.details

use_directory_urls: false
