[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hostlist"
dynamic = ["version"]
description = "A library for parsing and manipulating Slurm-style hostlists."
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.optional-dependencies]
dev = ["pytest", "mkdocs", "mkdocs-material", "mkdocstrings[python]", "cloudmesh-ai-theme"]

[project.scripts]
hostlist = "hostlist.cli:main"
hostlist-expand = "hostlist.cli:expand_wrapper"
hostlist-compact = "hostlist.cli:compact_wrapper"

[tool.setuptools.dynamic]
version = {attr = "hostlist.__version__"}

